# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [92]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np)

<module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>


#### 3. Create a null vector of size 10 (★☆☆)

In [15]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [10]:
np.shape(null_vector)

(10,)

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [17]:
six_vector = np.arange(10,50)
print(six_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [18]:
np.sort(six_vector)[::-1]
#six_vector.sort() 이건 내림차순 안됨

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [7]:
list1 = [1,2,0,0,4,0]
nonzero_index = []

for i in list1:
    if i != 0:
        nonzero_index.append(list1.index(i))
print(nonzero_index)

# list.index(element) : list내 element의 index 반환

[0, 1, 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [40]:
M1 = np.identity(3)
M2 = np.eye(3, dtype=float)
print(M1,'\n', M2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [44]:
np.random.random(27).reshape((3,3,3))

array([[[0.12231039, 0.14616004, 0.88402588],
        [0.81086343, 0.27850006, 0.04057657],
        [0.82483657, 0.37756536, 0.16944724]],

       [[0.49119534, 0.3712275 , 0.18424721],
        [0.38858723, 0.55698432, 0.23761824],
        [0.68504983, 0.65286122, 0.86058321]],

       [[0.68856192, 0.30742413, 0.6680265 ],
        [0.79525097, 0.04922293, 0.17096525],
        [0.84904274, 0.65697369, 0.27024168]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [51]:
M_10 = np.random.random(100).reshape((10,10))
print(np.min(M_10), np.max(M_10))

0.004788075736372299 0.991998277840805


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [52]:
M_30 = np.random.random(30).reshape(30,)
print(np.mean(M_30))

0.5431571628780373


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [22]:
array14 = np.zeros((6,6))

array14[(0,5),:]=1
array14[:,(0,5)]=1

print(array14)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [24]:
array14 = np.ones((6,6))
array14[1:-1, 1:-1] = 0  
print(array14)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 참고
* np.NaN / np.nan : NaN값(정해지지 않은 값) 불러옴 
* np.inf / -np.inf : 무한대/ 마이너스무한대 불러옴

In [28]:
0 * np.nan
# NaN값과 연산해도 그대로 NaN값으로 반환

nan

In [29]:
np.nan == np.nan
# NaN값은 자기자신과도 동일하지 않다.
# cf. None값은 자기자신과 동일하다.

False

In [31]:
np.inf > np.nan
# NaN값은 비교불가

False

In [32]:
np.nan - np.nan
# NaN값은 자기자신과도 동일하지 않다.
# NaN값과 연산해도 그대로 NaN값으로 반환

nan

In [33]:
np.nan in set([np.nan])
'''
'A' in set(['A'])
집합 안에 요소가 있는지 확인하는 식

집합 내 NaN값은 비교가능한가봄...
'''

True

In [38]:
set([np.nan])

{nan}

In [37]:
0.3 == 3*0.1
# 3*0.1 = 0.3000004
# 실수를 부동소수점으로 표현하여 정확한 값이 아니라 근사값으로 나타냄

False

In [36]:
3*0.1

0.30000000000000004

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [57]:
np.diag([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [42]:
array17 = np.ones((8,8))

array17[0:7:2, 0:7:2] = 0
array17[1:6:2, 1:6:2] = 0
print(array17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

#### 참고
* np.unravel_index(index, shape, order='C')

shape에 들어온 n차원 array를 flatten시킨후  
index위치에 존재하는 요소가  
기존 n차원 array에서는 어느 위치에 존재하는지 반환  

order='C':행(로우) 우선/ order='F':열(칼럼)우선  

(https://teang1995.tistory.com/14)

In [67]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

In [58]:
# 확인
A = np.arange(1,6*7*8+1).reshape((6,7,8))
print(A, "\n", A[1,5,3])

[[[  1   2   3   4   5   6   7   8]
  [  9  10  11  12  13  14  15  16]
  [ 17  18  19  20  21  22  23  24]
  [ 25  26  27  28  29  30  31  32]
  [ 33  34  35  36  37  38  39  40]
  [ 41  42  43  44  45  46  47  48]
  [ 49  50  51  52  53  54  55  56]]

 [[ 57  58  59  60  61  62  63  64]
  [ 65  66  67  68  69  70  71  72]
  [ 73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88]
  [ 89  90  91  92  93  94  95  96]
  [ 97  98  99 100 101 102 103 104]
  [105 106 107 108 109 110 111 112]]

 [[113 114 115 116 117 118 119 120]
  [121 122 123 124 125 126 127 128]
  [129 130 131 132 133 134 135 136]
  [137 138 139 140 141 142 143 144]
  [145 146 147 148 149 150 151 152]
  [153 154 155 156 157 158 159 160]
  [161 162 163 164 165 166 167 168]]

 [[169 170 171 172 173 174 175 176]
  [177 178 179 180 181 182 183 184]
  [185 186 187 188 189 190 191 192]
  [193 194 195 196 197 198 199 200]
  [201 202 203 204 205 206 207 208]
  [209 210 211 212 213 214 215 216]
  [217 218 219 220 221

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [84]:
array19 = np.random.random((5,5))
m, sd = array19.mean(), array19.std()
array19_nor = (array19-m)/sd
print(array19_nor)

[[-1.66623487 -0.90988743  1.37974298  0.80972207 -1.49851016]
 [-0.49514105  0.03777701  1.29764964 -0.78878252 -0.6229326 ]
 [-0.49609314  1.24479751  0.89122283  1.03077138  1.55043315]
 [-0.73511812  1.09279865  0.78107635 -0.37183434 -1.09722455]
 [-0.01088177 -1.23958401 -1.31314684  0.50025955  0.6291203 ]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [25]:
# 색상을 4바이트(RGBA)로 나타내는 사용자 지정 dtype을 생성하세요


color = np.dtype([ ("r", np.ubyte),
                    ("g", np.ubyte),
                      ("b", np.ubyte),
                       ("a", np.ubyte)])

## np.dtype : 사용자 지정 데이터타입 만들기
## np.ubyte : 부호없는 정수

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
array1 = np.random.random((5,3))
array2 = np.random.random((3,2))
np.dot(array1, array2)
## np.dot : 두 행렬의 곱

array([[1.05107607, 0.17278168],
       [1.20723138, 0.73074563],
       [0.86670741, 0.34593129],
       [0.89132173, 0.42152025],
       [1.07548577, 0.42843439]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
# 1차원 배열에서 3~8 사이 모든 요소를 음수화해라

A = np.arange(15)
A[(3<=A) & (A<=8)] *= -1
A

## 3 <= A <= 8 조건 표현식
## A *= a  -> A = A*a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [34]:
print(sum(range(5))) # =10
print( sum( range(5),-1 ) ) # =9

from numpy import * # ??
print( sum( range(5),-1 ) ) # =10

10
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [7]:
Z = np.arange(10)

print(Z**Z)
print(2 << Z >> 2) # 비트단위 시프트 연산자
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z) --> ilegal(에러발생)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)
print(arr1)
print(arr2)
print(np.intersect1d(arr1, arr2))

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [8]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

np.sqrt(-1) == np.emath.sqrt(-1)

nan
1j


C:\Users\user\AppData\Local\Temp\ipykernel_27924\1082418667.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
C:\Users\user\AppData\Local\Temp\ipykernel_27924\1082418667.py:4: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [9]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
next_year = np.datetime64('today', 'M') + np.timedelta64(1, 'M')
 
print(yesterday)
print(today)
print(tomorrow)
print(next_year)

2022-09-18
2022-09-19
2022-09-20
2022-10


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [20]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B) # A+B의 결과를 B에 할당해놓음
np.divide(A,2,out=A) # A/2의 결과를 A에 할당
np.negative(A,out=A) # -(A/2)를 A에 할당
np.multiply(A,B,out=A) # (A+B)*(-A/2)와 같은 결과
print(A)

[-1.5 -1.5 -1.5]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [21]:
z = np.random.uniform(0,10,10) # 양수의 무작위 원소 배열
print(z-z%1)
print(np.floor(z))
print(np.ceil(z))
print(z.astype(int))
print(np.trunc(z))

[5. 1. 2. 7. 8. 1. 2. 6. 5. 8.]
[5. 1. 2. 7. 8. 1. 2. 6. 5. 8.]
[6. 2. 3. 8. 9. 2. 3. 7. 6. 9.]
[5 1 2 7 8 1 2 6 5 8]
[5. 1. 2. 7. 8. 1. 2. 6. 5. 8.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [12]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [13]:
z = np.random.random(10)
z.sort()
print(z)

[0.0613295  0.26838547 0.29162547 0.40340179 0.4072364  0.54756966
 0.59496145 0.85017472 0.86694811 0.91294022]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [14]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
print(np.allclose(a, b))
print(np.array_equal(a, b))

False
False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [15]:
z = np.random.random((10, 2))
x, y = z[:,0],z[:,1] #x와 y에 각각 0열, 1열 할당
r = np.sqrt(x**2+y**2) # 데카르트 좌표로 표현
p = np.arctan2(y,x) # 극좌표계표현
print(r)
print(p)

[0.85017893 0.63684701 0.5881439  0.4807602  0.93913003 0.44639771
 0.68734346 0.96328721 0.02584123 0.37451319]
[0.32314519 0.69800924 0.8068443  0.96407589 1.08467668 0.37295087
 0.26330959 0.07431131 0.14041971 1.18667631]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [16]:
z = np.random.random(10)
print(z)
# 최대값 찾아 0으로 바꿈
z[np.argmax(z)] = 0
print(z)

[0.49520059 0.62251546 0.02820999 0.47080645 0.23472332 0.02357904
 0.31785076 0.5016496  0.80324422 0.8271382 ]
[0.49520059 0.62251546 0.02820999 0.47080645 0.23472332 0.02357904
 0.31785076 0.5016496  0.80324422 0.        ]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [17]:
# 주어진 값 = 7.3
num = 7.3
z = np.random.randint(0,10,10)
print(z)
# 주어진 값에서 가장 가까운 값 찾기
i = np.abs((z-num)).argmin()
# 가장 가까운값의 인덱스와 그 값 출력
print('인덱스:', i ,'/값:', z[i])

[1 6 2 8 1 5 8 7 9 6]
인덱스: 7 /값: 7


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [22]:
# ndenumerate() 사용
Z = np.arange(9).reshape(3,3)
print(Z)
for index, value in np.ndenumerate(Z):
    print(index, value)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [23]:
p=3 # 3개의 요소 배치
z = np.zeros((10,10)) #10x10의 빈 배열 생성
np.put(z, np.random.choice(range(10*10), p, replace=False), 7) #10x10 인덱스 안에서 p(3)만큼을 랜덤으로 선택하여 7을 삽입
print(z)

[[0. 7. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 7. 0. 0.]
 [0. 0. 0. 7. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [24]:
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[5 6 9]
 [0 6 9]
 [8 7 2]]
[[5 6 9]
 [0 6 9]
 [8 7 2]]


In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3