<a href="https://colab.research.google.com/github/lim-jr/ESAA/blob/main/0919%EC%9B%94%EA%B3%BC%EC%A0%9C_100_Numpy_Exercises(1~39).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np)

<module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
np.shape(null_vector)

(10,)

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
six_vector = np.arange(10,50)
print(six_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
np.sort(six_vector)[::-1]
#six_vector.sort() 이건 내림차순 안됨

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
list1 = [1,2,0,0,4,0]
nonzero_index = []

for i in list1:
    if i != 0:
        nonzero_index.append(list1.index(i))
print(nonzero_index)

# list.index(element) : list내 element의 index 반환

[0, 1, 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
M1 = np.identity(3)
M2 = np.eye(3, dtype=float)
print(M1,'\n', M2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
np.random.random(27).reshape((3,3,3))

array([[[0.12231039, 0.14616004, 0.88402588],
        [0.81086343, 0.27850006, 0.04057657],
        [0.82483657, 0.37756536, 0.16944724]],

       [[0.49119534, 0.3712275 , 0.18424721],
        [0.38858723, 0.55698432, 0.23761824],
        [0.68504983, 0.65286122, 0.86058321]],

       [[0.68856192, 0.30742413, 0.6680265 ],
        [0.79525097, 0.04922293, 0.17096525],
        [0.84904274, 0.65697369, 0.27024168]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
M_10 = np.random.random(100).reshape((10,10))
print(np.min(M_10), np.max(M_10))

0.004788075736372299 0.991998277840805


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
M_30 = np.random.random(30).reshape(30,)
print(np.mean(M_30))

0.5431571628780373


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array14 = np.zeros((6,6))

array14[(0,5),:]=1
array14[:,(0,5)]=1

print(array14)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
array14 = np.ones((6,6))
array14[1:-1, 1:-1] = 0  
print(array14)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 참고
* np.NaN / np.nan : NaN값(정해지지 않은 값) 불러옴 
* np.inf / -np.inf : 무한대/ 마이너스무한대 불러옴

In [ ]:
0 * np.nan
# NaN값과 연산해도 그대로 NaN값으로 반환

nan

In [ ]:
np.nan == np.nan
# NaN값은 자기자신과도 동일하지 않다.
# cf. None값은 자기자신과 동일하다.

False

In [ ]:
np.inf > np.nan
# NaN값은 비교불가

False

In [ ]:
np.nan - np.nan
# NaN값은 자기자신과도 동일하지 않다.
# NaN값과 연산해도 그대로 NaN값으로 반환

nan

In [ ]:
np.nan in set([np.nan])
'''
'A' in set(['A'])
집합 안에 요소가 있는지 확인하는 식

집합 내 NaN값은 비교가능한가봄...
'''

True

In [ ]:
set([np.nan])

{nan}

In [ ]:
0.3 == 3*0.1
# 3*0.1 = 0.3000004
# 실수를 부동소수점으로 표현하여 정확한 값이 아니라 근사값으로 나타냄

False

In [ ]:
3*0.1

0.30000000000000004

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
np.diag([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
array17 = np.ones((8,8))

array17[0:7:2, 0:7:2] = 0
array17[1:6:2, 1:6:2] = 0
print(array17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

#### 참고
* np.unravel_index(index, shape, order='C')

shape에 들어온 n차원 array를 flatten시킨후  
index위치에 존재하는 요소가  
기존 n차원 array에서는 어느 위치에 존재하는지 반환  

order='C':행(로우) 우선/ order='F':열(칼럼)우선  

(https://teang1995.tistory.com/14)

In [ ]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

In [ ]:
# 확인
A = np.arange(1,6*7*8+1).reshape((6,7,8))
print(A, "\n", A[1,5,3])

[[[  1   2   3   4   5   6   7   8]
  [  9  10  11  12  13  14  15  16]
  [ 17  18  19  20  21  22  23  24]
  [ 25  26  27  28  29  30  31  32]
  [ 33  34  35  36  37  38  39  40]
  [ 41  42  43  44  45  46  47  48]
  [ 49  50  51  52  53  54  55  56]]

 [[ 57  58  59  60  61  62  63  64]
  [ 65  66  67  68  69  70  71  72]
  [ 73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88]
  [ 89  90  91  92  93  94  95  96]
  [ 97  98  99 100 101 102 103 104]
  [105 106 107 108 109 110 111 112]]

 [[113 114 115 116 117 118 119 120]
  [121 122 123 124 125 126 127 128]
  [129 130 131 132 133 134 135 136]
  [137 138 139 140 141 142 143 144]
  [145 146 147 148 149 150 151 152]
  [153 154 155 156 157 158 159 160]
  [161 162 163 164 165 166 167 168]]

 [[169 170 171 172 173 174 175 176]
  [177 178 179 180 181 182 183 184]
  [185 186 187 188 189 190 191 192]
  [193 194 195 196 197 198 199 200]
  [201 202 203 204 205 206 207 208]
  [209 210 211 212 213 214 215 216]
  [217 218 219 220 221

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
array19 = np.random.random((5,5))
m, sd = array19.mean(), array19.std()
array19_nor = (array19-m)/sd
print(array19_nor)

[[-1.66623487 -0.90988743  1.37974298  0.80972207 -1.49851016]
 [-0.49514105  0.03777701  1.29764964 -0.78878252 -0.6229326 ]
 [-0.49609314  1.24479751  0.89122283  1.03077138  1.55043315]
 [-0.73511812  1.09279865  0.78107635 -0.37183434 -1.09722455]
 [-0.01088177 -1.23958401 -1.31314684  0.50025955  0.6291203 ]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
# 색상을 4바이트(RGBA)로 나타내는 사용자 지정 dtype을 생성하세요


color = np.dtype([ ("r", np.ubyte),
                    ("g", np.ubyte),
                      ("b", np.ubyte),
                       ("a", np.ubyte)])

## np.dtype : 사용자 지정 데이터타입 만들기
## np.ubyte : 부호없는 정수

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
array1 = np.random.random((5,3))
array2 = np.random.random((3,2))
np.dot(array1, array2)
## np.dot : 두 행렬의 곱

array([[1.05107607, 0.17278168],
       [1.20723138, 0.73074563],
       [0.86670741, 0.34593129],
       [0.89132173, 0.42152025],
       [1.07548577, 0.42843439]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
# 1차원 배열에서 3~8 사이 모든 요소를 음수화해라

A = np.arange(15)
A[(3<=A) & (A<=8)] *= -1
A

## 3 <= A <= 8 조건 표현식
## A *= a  -> A = A*a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5))) # =10
print( sum( range(5),-1 ) ) # =9
# sum(A,B) = A+B

from numpy import * # ??
print( sum( range(5),-1 ) ) # =10

10
9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(10)

print(Z**Z)
print(2 << Z >> 2) # 비트단위 시프트 연산자
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z) --> ilegal(에러발생)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0))
print(np.array(0) / np.array(0) ) # 나누면 nan
print(np.array(0) // np.array(0)) # 나누고 몫은 0
print(np.array([np.nan]).astype(int).astype(float)) 
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

# 이건 안찾아봄

0
nan
0
[-9.22337204e+18]
nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)
print(arr1)
print(arr2)
print(np.intersect1d(arr1, arr2))

# randint(start, end, number)

# 1차원 ndarray 집합에 대하여
# 1. unique(x) : 배열 내 중복된 원소 제거 후 유일한 원소를 정렬하여 반환
# 2. intersect1d(x, y) : 두 개의 배열 x, y 의 교집합을 정렬하여 반환
# 3. union1d(x, y) : 두 개의 배열 x, y의 합집합을 정렬하여 반환
# 4. in1d(x, y) : 첫번째 배열 x가 두번째 배열 y의 원소를 포함하고 있는지 여부의 불리언 배열을 반환
# 5. setdiff1d(x, y) : 첫번째 배열 x로 부터 두번째 배열 y를 뺀 차집합을 반환
# 6. setxor1d(x, y) : 두 배열 x, y의 합집합에서 교집합을 뺀 대칭차집합을 반환


array([2, 6, 0, 5])

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1)) # =nan
print(np.emath.sqrt(-1)) # =허수

np.sqrt(-1) == np.emath.sqrt(-1) # False

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

해석) 2016년 7월에 해당하는 모든 날짜를 어떻게 구하나요?

In [ ]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [ ]:
# 이건 뜬금없는데서 긁어옴

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
next_year = np.datetime64('today', 'M') + np.timedelta64(1, 'M')
 
print(yesterday)
print(today)
print(tomorrow)
print(next_year)

2022-09-19
2022-09-20
2022-09-21
2022-10


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

해석) 복사없이 (A+B)*(-A/2) 를 계산하는 방법은?

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B) # A+B의 결과를 B에 할당해놓음
np.divide(A,2,out=A) # A/2의 결과를 A에 할당
np.negative(A,out=A) # -(A/2)를 A에 할당
np.multiply(A,B,out=A) # (A+B)*(-A/2)와 같은 결과
print(A)

[-1.5 -1.5 -1.5]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
2가지 다른 방법을 이용하여, 양의 무작위원소배열에서 정수부분을 추출해라.

In [ ]:
z = np.random.uniform(0,10,10) # 양수의 무작위 원소 배열
print(z)
print(z%1) # 1로 나눈 나머지 = 소수점이하만 남음
print(z-z%1) # 소수점 이하 빼면 정수부분만 

print(np.floor(z)) 

print(np.ceil(z))
print(z.astype(int))
print(np.trunc(z))

[6.76046489 3.70520739 5.79874187 0.62658762 4.67209062 1.45510957
 8.45691792 3.61949433 8.65921289 3.07808606]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
z = np.random.random(10)
z.sort()
print(z)

[0.0613295  0.26838547 0.29162547 0.40340179 0.4072364  0.54756966
 0.59496145 0.85017472 0.86694811 0.91294022]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
print(np.allclose(a, b))
print(np.array_equal(a, b))

False
False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

카티지언 좌표(직교좌표)를 나타내는 임의의 10x2 행렬을 고려하여, 극좌표로 변환하시오.

In [ ]:
# 어레이
C = np.random.random((10,2)) # 임의의 10x2 행렬 생성
x, y = A[:,0], A[:,1] # x, y에 할당

rho = np.sqrt(x**2+y**2) # sqrt 루트
theta = np.arctan2(y,x) 
# arctan1: 출력범위가 [-pi/2, +pi/2]
# arctan2: 출력범위가 [-pi, +pi]

# P = np.concatenate([rho, theta], axis=1)
## 위 코드 오류 뜨는 이유 : rho, theta가 1차원 array라 가로방향으로 결합이 안됨
## axis=1 : 열방향 결합 
P = np.concatenate([rho.reshape(10,1), theta.reshape(10,1)], axis=1)

print("직교좌표계 C : \n", C)
print("\n")
print("극좌표계 P : \n", P)

직교좌표계 C : 
 [[0.26689488 0.11466826]
 [0.58453673 0.88377966]
 [0.48133358 0.40852932]
 [0.29869047 0.194194  ]
 [0.71865791 0.35011988]
 [0.27685498 0.18586988]
 [0.66572629 0.07183588]
 [0.23203854 0.91696379]
 [0.41071462 0.23244561]
 [0.12313947 0.2328485 ]]


극좌표계 P : 
 [[0.87398513 0.44941646]
 [0.73720175 1.36939365]
 [1.01896794 1.11541503]
 [0.882419   0.94040373]
 [1.32189435 0.85463972]
 [1.21898099 0.93037599]
 [0.98010956 1.45083093]
 [1.1733874  0.6181197 ]
 [0.90667553 0.28408773]
 [0.98801064 0.89676433]]


In [ ]:
# 데이터 프레임
import pandas as pd
C = pd.DataFrame(np.random.random((10,2)), columns=['x', 'y'])

rho = pd.DataFrame(np.sqrt(x**2+y**2))
theta = pd.DataFrame(np.arctan2(y,x))

P = pd.concat([rho, theta], axis=1) 
P.columns = ['rho', 'theta']

print("직교좌표계 C : \n", C)
print("\n")
print("극좌표계 P : \n", P)

# 데이터프레임 합칠 때 : concat(), merge(), join()
## merge(), join()은 key를 기준으로 교집합/합집합으로 합치기
## concat()는 key가 없을 때 합치기, inner, outer 옵션으로 교집합/합집합

<class 'pandas.core.frame.DataFrame'>
직교좌표계 C : 
           x         y
0  0.735241  0.904674
1  0.234409  0.595520
2  0.856039  0.010348
3  0.358626  0.344015
4  0.483917  0.107209
5  0.411989  0.957575
6  0.044408  0.137487
7  0.699067  0.875456
8  0.731331  0.605617
9  0.374775  0.376295


극좌표계 P : 
         rho     theta
0  0.873985  0.449416
1  0.737202  1.369394
2  1.018968  1.115415
3  0.882419  0.940404
4  1.321894  0.854640
5  1.218981  0.930376
6  0.980110  1.450831
7  1.173387  0.618120
8  0.906676  0.284088
9  0.988011  0.896764


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

크기가 10인 랜덤벡터를 생성하고, 최댓값을 0으로 바꿔라.

In [ ]:
Z = np.random.randint(0,100,10)
print(Z)
print(np.argmax(Z)) # 최댓값이 위치한 인덱스를 반환

Z[np.argmax(Z)] = 0
print(Z)

[ 7 17 24 89 53 75 29 88 49 59]
3
[ 7 17 24  0 53 75 29 88 49 59]


In [ ]:
# 최댓값이 2개 이상이라면 ??????
A = np.random.randint(0,5,10)
print(A)
print(np.argmax(A)) # 최댓값이 2개이상 있을 때 가장 앞쪽것만 표시

# 루프 
list1 = list(np.random.randint(0,5,10))
max_index =[]
for i in list1:
  if i == max(list1):
    max_index.append(list1.index(i))

print(list1)
print(max_index)


list2 = list(np.random.randint(0,5,10))
max_index = []
for i in list2 :
  if i == max(list2):

  print(list2.index(i))
print(list2)

IndentationError: ignored

In [ ]:
a=[1,2,3,4,5]
a.index(3)

2

In [ ]:
# (이건 그냥 궁금) 2차원 어레이에서 

A = np.array([[1,2,3], [10,20,30]])
print(A)
print(np.argmax(A)) # 축설정하지 않으면 1차원 어레이로 flatten상태로 가정
print(np.argmax(A, axis=0)) # 세로축(열) 원소끼리 비교
print(np.argmax(A, axis=1)) # 가로축(행) 원소끼리 비교

[[ 1  2  3]
 [10 20 30]]
5
[1 1 1]
[2 2]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

Z벡터에서 주어진 스칼라에서 가장 가까운 값을 찾으려면?

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(Z, v)
min_index = (np.abs(Z-v)).argmin()
# 벡터와 스칼라 간의 차를 구해서 거리가 가장 작은 값을 찾기
# np.abs(x): x의 절댓값
# array.argmin(): array의 최솟값이 위치한 인덱스
print(Z[min_index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 12.982520171307943
13


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

어레이에 대한 인덱스 좌표 구해라

In [ ]:
# enumerate(): 리스트의 원소에 인덱스를 부여하고 튜플형태로 반환

## enumerate() 쓰지 않을 때
i = 0
for letter in ['A', 'B', 'C']:
  print(i, letter)
  i += 1
## enumerate() 쓸 때 
for i_letter in enumerate(['A','B','C']):
  print(i_letter)

0 A
1 B
2 C
(0, 'A')
(1, 'B')
(2, 'C')


In [ ]:
# np.ndenumerate(): ndarray의 원소에 인덱스 좌표를 부여해주는 함수

A = np.array([[1,10],[2,20]])
for index in np.ndenumerate(A):
  print(index)

((0, 0), 1)
((0, 1), 10)
((1, 0), 2)
((1, 1), 20)


In [ ]:
Z = np.arange(9).reshape(3,3)

for index, element in np.ndenumerate(Z):
  print(index, element)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

2차원 어레이에서 p를 랜덤하게 배치하려면?

In [ ]:
# n = 'size of a 2D array'(2차원 어레이)
# p = 'the number of elements that you want to place'(랜덤하게 배치할 값의 개수)
n = 10
p = 4
Z = np.zeros((n,n))

# np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
# 1. 랜덤하게 배치할 인덱스를 생성
randindex = np.random.choice(range(n*n), p, replace=False)
# 2. Z어레이의 랜덤한 인덱스 위치에 p개의 value를 배치
np.put(Z, randindex, 365)

## np.random.choice(end, n, replace=F): 0이상, end미만인 정수 중 n개 출력, 비복원
## = np.random.randint(start=0, end, n, replace=F) 와 같은 결과 출력
## np.put(Arr, index, value ): Array의 지정한 index의 값을 value로 바꾼다. 


print(Z)

[[  0.   0.   0.   0.   0.   0.   0.   0.   0. 365.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0. 365.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0. 365.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 365.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

n번째 열로 어레이를 정렬하려면?

In [ ]:
Z = np.random.randint(0,10, (3,3))
n=3
Z_sort = Z[Z[:,n-1].argsort()] 
# 세번째 열(index=2)을 기준으로 정렬하는 인덱스를 저장
## 세번째 열 : [6,3,5]->[3,5,6] (매번 달라짐)

print(Z)
print(Z[:,n-1].argsort())
print(Z_sort)

[[5 5 0]
 [3 6 6]
 [8 7 5]]
[0 2 1]
[[5 5 0]
 [8 7 5]
 [3 6 6]]


In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3